In [2]:
print('hello world')

hello world

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('fake_data.csv')
print(df)

     Hex_ID Barangay_name         PCSG  Population_density*  Latitude  \
0       267  Batong Buhay  PH175109001             15151504       NaN
1       268  Batong Buhay  PH175109001               124322       NaN
2       303  Batong Buhay  PH175109001                15654       NaN
3       304  Batong Buhay  PH175109001                   10       NaN
4       305  Batong Buhay  PH175109001              1455896       NaN
..      ...           ...          ...                  ...       ...
144     487        Burgos  PH175109003                 2094       NaN
145     488        Burgos  PH175109003                13180       NaN
146     521        Burgos  PH175109003                27627       NaN
147     522        Burgos  PH175109003                19946       NaN
148     523        Burgos  PH175109003                12161       NaN

     Longitude  Buildability  RHU_in_area
0          NaN           NaN            0
1          NaN           NaN            0
2          NaN           NaN            1
3          NaN           NaN            0
4          NaN           NaN            0
..         ...           ...          ...
144        NaN           NaN            1
145        NaN           NaN            1
146        NaN           NaN            0
147        NaN           NaN            0
148        NaN           NaN            0

[149 rows x 8 columns]

## Get columns

In [10]:
pop_den = df.loc[:,"Population_density*"]
pop_den

0      15151504
1        124322
2         15654
3            10
4       1455896
         ...
144        2094
145       13180
146       27627
147       19946
148       12161
Name: Population_density*, Length: 149, dtype: int64

In [11]:
rhu_in_area = df.loc[:, "RHU_in_area"]
rhu_in_area

0      0
1      0
2      1
3      0
4      0
      ..
144    1
145    1
146    0
147    0
148    0
Name: RHU_in_area, Length: 149, dtype: int64

## HCI Formula

In [ ]:
HCI = total_ai - (total_ai)*(yi)

In [20]:
# creating a list of dataframe columns
pop_den_list = list(pop_den)

i = 0
for i in pop_den_list:
    # printing a third element of column
    print(i)

15151504
124322
15654
10
1455896
45657
15914
21062
11627
20856
2864
5171
7549
15909
2395
10546
13640
7066
8394
27883
21497
24182
17022
29982
472
22871
2045
26134
25694
1763
11309
16929
29304
10705
19764
15410
1710
16642
6919
11086
15227
6177
22624
4797
6361
22068
14453
14911
5387
5076
2797
28703
12668
12681
16092
7091
444
2249
28273
6180
6447
28191
3749
15248
21887
20588
11746
27970
20861
6615
11922
11729
21267
15880
16606
28888
8727
6545
1929
3859
14900
748
457
660
29877
5456
1697
7524
25095
18441
4100
17840
8394
18528
12792
20444
16465
24700
1406
16906
2004
29997
13869
29008
23365
13451
13008
26178
13460
16505
7211
38
12029
9570
14241
21649
1189
19453
2558
26351
18446
9447
15265
1361
4030
20852
19879
22482
530
17615
8798
8444
2367
14651
20293
24435
20657
5161
28383
20428
15438
13052
11797
24837
2094
13180
27627
19946
12161
[15151504, 124322, 15654, 10, 1455896, 45657, 15914, 21062, 11627, 20856, 2864, 5171, 7549, 15909, 2395, 10546, 13640, 7066, 8394, 27883, 21497, 24182, 17022, 29982, 472, 22871, 2045, 26134, 25694, 1763, 11309, 16929, 29304, 10705, 19764, 15410, 1710, 16642, 6919, 11086, 15227, 6177, 22624, 4797, 6361, 22068, 14453, 14911, 5387, 5076, 2797, 28703, 12668, 12681, 16092, 7091, 444, 2249, 28273, 6180, 6447, 28191, 3749, 15248, 21887, 20588, 11746, 27970, 20861, 6615, 11922, 11729, 21267, 15880, 16606, 28888, 8727, 6545, 1929, 3859, 14900, 748, 457, 660, 29877, 5456, 1697, 7524, 25095, 18441, 4100, 17840, 8394, 18528, 12792, 20444, 16465, 24700, 1406, 16906, 2004, 29997, 13869, 29008, 23365, 13451, 13008, 26178, 13460, 16505, 7211, 38, 12029, 9570, 14241, 21649, 1189, 19453, 2558, 26351, 18446, 9447, 15265, 1361, 4030, 20852, 19879, 22482, 530, 17615, 8798, 8444, 2367, 14651, 20293, 24435, 20657, 5161, 28383, 20428, 15438, 13052, 11797, 24837, 2094, 13180, 27627, 19946, 12161]

In [16]:
# creating a list of dataframe columns
rhu_in_area_list = list(rhu_in_area)

for i in rhu_in_area_list:
    # printing a third element of column
    print(i)

0 0
1 0
2 1
3 0
4 0
5 1
6 0
7 0
8 1
9 0
10 0
11 1
12 1
13 1
14 1
15 1
16 0
17 0
18 0
19 0
20 1
21 0
22 0
23 1
24 1
25 1
26 0
27 0
28 1
29 0
30 0
31 1
32 0
33 1
34 0
35 0
36 0
37 0
38 1
39 1
40 1
41 0
42 1
43 0
44 0
45 1
46 1
47 1
48 0
49 1
50 1
51 0
52 0
53 0
54 0
55 1
56 0
57 1
58 0
59 1
60 0
61 1
62 1
63 0
64 1
65 0
66 0
67 0
68 0
69 1
70 1
71 0
72 0
73 1
74 0
75 1
76 0
77 0
78 1
79 1
80 1
81 0
82 1
83 1
84 0
85 0
86 0
87 0
88 0
89 1
90 0
91 0
92 1
93 0
94 0
95 1
96 0
97 0
98 1
99 0
100 1
101 1
102 1
103 0
104 0
105 1
106 0
107 1
108 1
109 0
110 1
111 1
112 0
113 1
114 1
115 0
116 1
117 1
118 1
119 1
120 0
121 0
122 0
123 1
124 0
125 0
126 0
127 1
128 1
129 0
130 1
131 0
132 1
133 0
134 1
135 1
136 0
137 0
138 1
139 1
140 1
141 0
142 1
143 1
144 1
145 1
146 0
147 0
148 0